#!/bin/bash
echo "=== FULL RASPBERRY PI DIAGNOSTIC (camera / surveillance focused) ==="
echo "Hostname: $(hostname) | Date: $(date)"
echo ""

echo "=== HARDWARE ==="
echo "Device Model: $(tr -d '\0' < /proc/device-tree/model 2>/dev/null || echo 'N/A')"
echo "OS / Release: $(grep PRETTY_NAME /etc/os-release | cut -d= -f2 | tr -d '\"')"
echo "Kernel: $(uname -a)"
echo "Memory (RAM):"
free -h
echo "CPU Temp: $(vcgencmd measure_temp 2>/dev/null || echo 'N/A')"
echo ""

echo "=== STORAGE ==="
echo "All block devices:"
lsblk -o NAME,SIZE,RO,TYPE,TRAN,FSTYPE,MOUNTPOINTS,UUID -d 2>/dev/null | column -t
echo ""
echo "Filesystem usage:"
df -h -x tmpfs -x devtmpfs
echo ""

echo "=== CAMERA ==="
echo "rpicam-hello --list-cameras:"
rpicam-hello --list-cameras 2>&1 || echo "rpicam-hello not available"
echo ""
echo "rpicam-apps / libcamera version:"
rpicam-hello --version 2>&1 || echo "rpicam-hello not available"
echo ""
echo "Legacy vcgencmd get_camera:"
vcgencmd get_camera 2>&1 || echo "N/A"
echo ""

echo "=== MEDIAMTX (core of the system) ==="
echo "Service status:"
systemctl status mediamtx.service --no-pager -l 2>&1 | head -25 || echo "mediamtx.service not found"
echo ""
echo "MediaMTX config (mediamtx.yml):"
cat ~/mediamtx.yml 2>/dev/null || echo "No ~/mediamtx.yml found"
echo ""
echo "Recent MediaMTX logs (last 15 lines):"
journalctl -u mediamtx.service -n 15 --no-pager 2>&1 || echo "No logs"
echo ""

echo "=== UPLOAD SCRIPT & LOG ==="
echo "upload_to_pi5.sh:"
cat ~/upload_to_pi5.sh 2>/dev/null || echo "No upload script found"
echo ""
echo "upload.log (last 20 lines):"
tail -20 ~/upload.log 2>/dev/null || echo "No upload.log"
echo ""

echo "=== VIDEO FILES ==="
echo "Directory listing:"
ls -lah ~/videos/ ~/videos/cam/ 2>/dev/null || echo "No videos directories on this host"
echo ""
echo "surveillance_drops (Pi 5 side):"
ls -lah ~/surveillance_drops 2>/dev/null | tail -20 || echo "No surveillance_drops on this host"
echo ""
echo "Disk usage of videos:"
du -sh ~/videos ~/surveillance_drops 2>/dev/null || echo "N/A"
echo ""

echo "=== CRON JOBS ==="
echo "User crontab:"
crontab -l 2>/dev/null || echo "No user crontab"
echo ""
echo "Root crontab:"
sudo crontab -l 2>/dev/null || echo "No root crontab (or sudo failed)"
echo ""

echo "=== VIDEO-RELATED PACKAGES ==="
dpkg -l | grep -E 'libcamera|picamera|ffmpeg|motion|gstreamer|v4l|rpicam' || echo "none found"
echo ""

echo "=== NETWORKING ==="
echo "IP addresses:"
ip -brief addr show
echo "Routing table:"
ip route
echo ""
echo "Ping Pi 5 (10.0.0.23):"
ping -c 3 -W 2 10.0.0.23 2>&1 || echo "Cannot reach Pi 5"
echo ""
echo "Ping Jetson (10.0.1.69):"
ping -c 3 -W 2 10.0.1.69 2>&1 || echo "Cannot reach Jetson"
echo ""

echo "=== AI SOFTWARE (for reference) ==="
echo "llama.cpp:"
command -v llama-cli llama-server llama-bench 2>/dev/null || echo "llama.cpp binaries not in PATH"
ls ~/llama.cpp/build/bin/llama* 2>/dev/null | head -5 || echo "No llama.cpp build in ~/llama.cpp"
echo ""
echo "GGUF models:"
find ~ -name "*.gguf" 2>/dev/null | head -10 || echo "No .gguf files"
echo ""

echo "=== END OF DIAGNOSTIC ==="
